# docker-compose.yml

services:
  nginx-modsec:
    container_name: waf-service
    image: owasp/modsecurity-crs:3.3.5-nginx-202308071108
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # THÊM LẠI DÒNG NÀY:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - config_volume:/etc/nginx/config
    # Các biến môi trường bây giờ không còn tác dụng với Nginx nữa, 
    # nhưng vẫn cần cho ModSecurity.
    environment:
      - MODSEC_RULE_ENGINE=On
      - MODSEC_AUDIT_LOG=/dev/stdout
      - MODSEC_AUDIT_LOG_TYPE=Serial
      - MODSEC_AUDIT_LOG_FORMAT=JSON
    depends_on:
      - dashboard
    restart: always
  
  # ... dịch vụ dashboard giữ nguyên ...
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9002:9002"
    volumes:
      - .:/app 
      - /app/node_modules
      - config_volume:/app/config
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}

volumes:
  config_volume: